### ISSUE TITLE
Formatting of donut chart labels

### ISSUE THREAD

**Issue by cute0laf** [TaoStats/bittensor-explorer-ui#109]
![image](https://github.com/TaoStats/bittensor-explorer-ui/assets/53915161/7ccda5a4-48a1-4686-bf1d-cac4544ab77d)

The number shown in this image is not properly formatted.

It should be formatted at 4,535,379

**Comment by TopETH** [comment]
@cute0laf 

I would like to bring attention to a challenge regarding the issue at hand. The current situation pertains to the representation of data in the chart. While the chart accurately displays numerical values, it is not designed to interpret formatted strings when they are included as part of the chart data.

To elaborate further, the "series" property of the chart component specifically expects numerical values as input, rather than formatted strings. Therefore, incorporating a formatted string directly into the chart data would impede its ability to analyze the data effectively.
